### ISSUE TITLE
Undefined variable $access_data

### ISSUE THREAD

**Issue by x2luilop** [mercadopago/DEPRECATED-sdk-php#1]
I downloaded the sdk before you made any changes to the repository, After downloading it with the new changes I got this message: Undefined variable $access_data (Line Number: 40)

It turns out the method get_access_token() doesn't have this line: 

$access_data = MPRestClient::post ("/oauth/token", $appClientValues, MPRestClient::MIME_FORM);

Therefore we can't authenticate into MercadoPago and we get the undefined message

**Comment by hcasatti** [comment]
Fixed...
