### ISSUE TITLE
Ver un Pago en https://api.mercadolibre.com/collections/notifications/

### ISSUE THREAD

**Issue by ceciunt** [mercadopago/DEPRECATED-sdk-php#100]
Hola! qué tal?

Estuve probando con Sandbox el tema de las notificaciones IPN de MercadoPago, y todo ok. El tema es que quiero probar cómo recibir los datos de un pago realizado, y como no se puede probar con sandbox (tengo entendido eso, ya que a comprar no figura el pago en el usuario), quise probar con una compra ya realizada de un usuario que ya ha realizado ventas.

Pero al poner el id y token en 
https://api.mercadolibre.com/collections/notifications/{id}?access_token={token} 
me tira:

Payments Notification
Consulta un pago que fue informado por medio de la IPN
http://prntscr.com/hgemx8

Asi que la pregunta es... si o si tengo que hacer una compra real, hacer que haga la notificación, para finalmente probar como recibir/ver los datos del token?.

Gracias

**Comment by joelibaceta** [comment]
El endpoint "/collections/notifications" ha sido deprecado, ver nota de deprecación https://www.mercadopago.com.ar/developers/es/guides/localization/migrating-v0-v1
