### ISSUE TITLE
Api payment ya no entrega email de pagador

### ISSUE THREAD

**Issue by truchosky** [mercadopago/DEPRECATED-sdk-php#105]
estimados,
en mercado pago, por medio de la API cuando recibo un pago obtengo algunos datos del comprador, entre ellos el correo para enviar un código automático, sigo la documentación y obtengo todo menos el email, hay algun problema con la API o yo esoty haciendo algo mal?,

echo $payment_info["response"]["collection"]["payer"]["first_name"]; -> nombre correcto del pagador
echo $payment_info["response"]["collection"]["payer"]["email"]; -> nada, en blanco
echo $payment_info["response"]["collection"]["payer"]["nickname"]; -> nickname correcto del pagador

doc: https://www.mercadopago.cl/developers/es/api-docs/account/payments/older-integrations/

**Comment by truchosky** [comment]
wtf?, where is mercado pago people ?

**Comment by gacortezia** [comment]
Hello truchsky,

I'm having the same problem, did you solve it?

**Comment by gacortezia** [comment]
> wtf?, where is mercado pago people ?
I'm having the same problem, did you solve it?

**Comment by joelibaceta** [comment]
Es correcto, se envía el id del usuario con el cual puedes consultar al API de users ( `/users/:id` ).
