### ISSUE TITLE
Mercado Envíos API - Habilitar todos los métodos/formas de envío?

### ISSUE THREAD

**Issue by Niko-EstudioBL** [mercadopago/DEPRECATED-sdk-php#114]
Buenas!

Contamos con un ccommerce integrado con mercado pago y mercado envíos. Al crear la preferencia de pago, incluímos la información para el envío, como la documentación indica:

`"shipments" => array(
        "mode" => "me2",
        "dimensions" => "30x30x30,500",
        "local_pickup" => true,
        "default_shipping_method" => 501045
)`

El inconveniente radica en que al momento de efectuar el pago, solo permite seleccionar retirar por local o envío normal a domicilio (sin especificar más nada). Existe posibilidad (debería) de mostrar todas las opciones posibles? Sean envío a domicilio normal y/o prioritario, posibilidad de retirar por sucursal, etc.

Aguardo respuestas, muchas gracias de antemano.

**Comment by mvconline1** [comment]
¡Hola! ¿Lo pudiste resolver?

A mi me pasa lo mismo o similar. Solo me aparece la opción de envío normal y no otros opciones. 

Al mismo tiempo, al habilitar Mercado Envíos me deshbilita el resto de las opciones de Pago, lo que no debería suceder de esa forma.

**Comment by plencovich** [comment]
Buenas, hay novedades? Estoy en la misma situación.

**Comment by joelibaceta** [comment]
Este canal no esta destinado al soporte general sobre el funcionamiento de productos de MercadoPago, para soporte general sobre otros servicios, APIs o productos contactarse al canal de soporte tecnico oficial. http://mercadopago.com.ar/developers/es/support/
