### ISSUE TITLE
Usuarios de Prueba - Sandbox

### ISSUE THREAD

**Issue by maxiz22** [mercadopago/DEPRECATED-sdk-php#116]
Buenas , a ver si alguien me puede dar una mano por favor .
Me canse de buscar como hacer andar el checkout del sandbox .

Cree 2 usuarios de prueba siguiendo esta guia:
https://www.mercadopago.cl/developers/es/solutions/payments/basic-checkout/test/test-users/

Hasta ahi todo bien , le saque el CLIENT_ID Y el CLIENT_SECRET a uno de los usuarios de prueba para usuarlo como vendedor y lo puse en mi aplicacion, cree el boton de pago definiendo:
$mp->sandbox_mode(true);
y en el boton la url se dirige al sandbox_init_point.

En otra ventana en incognito me logueo con mi otro usuario de prueba en MP y voy a darle click a mi boton para comprarle a mi otro usuario de prueba pero todas las tarjetas que dicen aca:
https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/test/basic-sandbox/

NO FUNCIONAN , me dan error de que visa no pudo procesar su pago.
Tengo que probar el IPN antes de mandar a produccion ya que es parte critica de la aplicación.

Tambien probe con init_point sin sandbox y pasa lo mismo.
¿Esto funciona todavia? ¿ Estoy haciendo algo mal? Aparte cabe recalcar que en las guias de MP no aclara que para que el sandbox funcione correctamente necesitamos utilizar 2 usuarios de prueba como lei en otras respuestas.
Desde ya muchas gracias saludos!

**Comment by maxiz22** [comment]
Bueno encontre la solucion , pude hacer un pago.Las tarjetas de la guia estan mal
las que funcionan actualmente se encuentran en este link:
https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/test-cards/

**Comment by knifesk** [comment]
Los usuarios de prueba son para probar en modo producción... El sandbox no
funciona hace banda.. la unica forma de probar es en live con usuario de
prueba

Saludos
