### ISSUE TITLE
Documentación eliminada?

### ISSUE THREAD

**Issue by knifesk** [mercadopago/DEPRECATED-sdk-php#117]
Qué pasó con los documentos de las suscripciones del basic checkout??? por que no están???

https://www.mercadopago.com.ar/developers/en/api-docs/basic-checkout/subscription-preferences/

**Comment by joelibaceta** [comment]
@knifesk fue un problema temporal, pero es bueno agregar que los APIs de suscripciones están en medio de un proceso de refactor importante.
