### ISSUE TITLE
v0.5.2 y 0.5.3 - searchPayments - Error 404 

### ISSUE THREAD

**Issue by vousys** [mercadopago/DEPRECATED-sdk-php#118]
Chicos dejo de andar la v "0.5.2" y actualice con la "0.5.3" pero sigue arrojando lo mismo.
Estoy buscando pagos por el external reference

```
$filters["external_reference"] =$referencia; 
$payment_info = $mp->search_payment($filters,0,2);

```

La v0.5.2 me devolvia

Leyendo OP#24 trans:272247088-8d650229-5e0f-4353-8b72-56b3bafafe54
get_payment_info:
```
Array
(
    [status] => 404
    [response] => Array
        (
            [message] => Resource /collections/notifications/272247088-8d650229-5e0f-4353-8b72-56b3bafafe54 not found.
            [error] => not_found
            [status] => 404
            [cause] => Array
                (
                )

        )
)

```
Y la v 0.5.3 me devuelve

`Fatal error: Uncaught exception 'MercadoPagoException' with message 'Not Found' in /var/www/clients/client1/web1/web/XXX/frameworks/mp/lib/mercadopago.php:448 Stack trace: #0 /var/www/clients/client1/web1/web/XXXX/frameworks/mp/lib/mercadopago.php(465): MPRestClient::exec(Array) #1 /var/www/clients/client1/web1/web/XXXX/frameworks/mp/lib/mercadopago.php(74): MPRestClient::get(Array) #2 /var/www/clients/client1/web1/web/XXXX/frameworks/mp/lib/mercadopago.php(78): MP->get_payment('272247088-3c290...') #3 /var/www/clients/client1/web1/web/XXX/crons/mercadopago-ipn.php(76): MP->get_payment_info('272247088-3c290...') #4 {main} thrown in `

**Comment by joelibaceta** [comment]
@vousys disculpa la tarda respuesta, efectivamente como comentamos en el sitio para desarrolladores (https://www.mercadopago.com.ar/developers//es/guides/localization/migrating-v0-v1/), estamos en proceso de migración de endpoints por lo que recomendamos actualizar el sdk a la ultima versión en master o migrar a la nueva version del SDK https://github.com/mercadopago/dx-php
