### ISSUE TITLE
Es posible utilizar este sdk desde Chile

### ISSUE THREAD

**Issue by t10barba** [mercadopago/DEPRECATED-sdk-php#12]
He seguido todos los pasos pero mis consultas siempre obtienen como resultado lo siguiente:

array(2) { ["status"]=> int(0) ["response"]=> NULL }

Los datos "CLIENT_ID" y "CLIENT_SECRET" los obtuve desde la siguiente URL.

https://www.mercadopago.com/mlc/cartdata

**Comment by luisj135** [comment]
Desde colombia me pasa lo mismo  pero subi el archivo adicional cacert.pem y ya funciono
