### ISSUE TITLE
Problemas con la búsqueda de pagos

### ISSUE THREAD

**Issue by raikel** [mercadopago/DEPRECATED-sdk-php#120]
Hola, al parecer la búsqueda de pagos de la API no funciona correctamente. En la primera foto que adjunto se puede ver que existe un pago con una referencia 5b2f01975f50a en la cuenta del vendedor y que cuando realizo una búsqueda con esta referencia no devuelve ningún resultado.
![screenshot_1](https://user-images.githubusercontent.com/23200453/41820282-e8ba2f28-7794-11e8-955f-0f8c9b785970.png)
![screenshot_2](https://user-images.githubusercontent.com/23200453/41820283-ebfd3130-7794-11e8-869b-d652331c7ca1.png)

**Comment by emiliodeg** [comment]
Después de días intentando hacerlo funcionar, caí en cuenta que la versión 0.5.2 tiene 3 años sin actualizarse, intente con `composer require mercadopago/sdk:dev-master` y todo comenzó a funcionar. 
Espero te sirva, suerte

**Comment by joelibaceta** [comment]
@emiliodeg efectivamente, esto por que deprecamos el endpoint `/collections` el cual actualizamos a `/v1/payments`.
