### ISSUE TITLE
¿Las notificaciones de ipn funcionan en modo sandbox?

### ISSUE THREAD

**Issue by leamasuero** [mercadopago/DEPRECATED-sdk-php#121]
¿Las notificaciones de ipn funcionan en modo sandbox?

¿Existe alguna pagina donde se listen los estados de los servicios de mercadopago?

**Comment by knifesk** [comment]
Yo en sandbox no pude probar absolutamente nada... Te recomendaría que uses usarios de prueba en **modo live**... tenes que crear un usuario vendedor y configurar tu APP con el public/secret/token de ese usuario y luego crear usuarios de prueba para usarlos de comprador.

https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/test/test-users/

Saludos

**Comment by leamasuero** [comment]
Gracias @knifesk . Hice exactamente eso, pero no hay caso.
- Tengo los usuarios de prueba: tanto para el vendedor como el comprador.
- Creo la orden exitosamente.
- El retorno success de la creación de la orden me informa un `collection_id`.

Estoy queriendo saber que clase de información es la que tiene un ipn (puesto que nunca la he visto y no he encontrado documentación al respecto).

Estoy intentando por el momento, consultar el estado según esta url que encontré en alguna consulta en el foro:

`https://api.mercadopago.com/collections/notifications/14983861?access_token=TEST-7135447890570238-071518-18d4cb4b41bf1ee4d5607aa249f1aad8-336920704#json`


Pero me devuelve un `bad request`:

```
{
  "message": "14983861 could not be obtained",
  "error": "bad_request",
  "status": 400,
  "cause": [
  ]
}
```

Lo mismo sucede con el `access_token` productivo.
Se hace muy difícil integrar mercadopago de esta manera. No es seria la documentación, ni el soporte.

**Comment by joelibaceta** [comment]
El endpoint `/collection/notifications/` ha sido deprecado, se debe usar `/v1/payments/ `en su lugar, (ver nota de deprecación https://www.mercadopago.com.ar/developers/es/guides/localization/migrating-v0-v1)
