### ISSUE TITLE
Problema con el ejemplo de boton_full.php

### ISSUE THREAD

**Issue by Ceroonda** [mercadopago/DEPRECATED-sdk-php#122]
Estoy teniendo un problema con el popup donde se hace la transacción... una vez finalizada, debería cerrarse el popup y ejecutar las URL que estan seteadas como back_urls... hace unos meses funcionaba lo mas bien, hoy el popup no se cierra y se refresca la url directamente en el popup.

Me baje la ultima version e hice la prueba y sigue pasando lo mismo.

Entiendo no hay nada que configurar de mi lado para que esto suceda... es correcto?

Muchas gracias, atte!

![screen shot 2018-07-19 at 6 35 48 pm](https://user-images.githubusercontent.com/41452706/42971448-b4c2e6ea-8b82-11e8-9ffc-74e14b95f3eb.png)

![screen shot 2018-07-19 at 6 36 22 pm](https://user-images.githubusercontent.com/41452706/42971468-cbe25c7a-8b82-11e8-9436-2ca5eba70178.png)

**Comment by joelibaceta** [comment]
Hola @Ceroonda  te comento que este canal esta destinado únicamente a la discusión de bugs sobre el SDK legacy para PHP, el error que nos comentas no esta relacionado al SDK sino al funcionamiento del Checkout Web, te comparto el canal de soporte tecnico oficial https://www.mercadopago.com.ar/developers/es/support.
