### ISSUE TITLE
Invalid value for transaction amount

### ISSUE THREAD

**Issue by Luis0719** [mercadopago/DEPRECATED-sdk-php#123]
Hola!

Estoy tratando de implementar mercagopago en mi página, pero estoy teniendo problemas con el valor flotante de la cantidad a pagar. Cuando imprimo la información de los datos de pago la cantidad aparece correctamente (2.32).

{ ["transaction_amount"]=> float(2.32) }

Pero a la hora de proceder con el pago me sale el siguiente error:

<img width="1033" alt="ErrorImg" src="https://user-images.githubusercontent.com/24446572/43088416-b205e7c6-8e67-11e8-8470-9957f26ff085.png">

**Comment by joelibaceta** [comment]
@Luis0719 eso es por que el monto es inferior al mínimo permitido para una transacción.
