### ISSUE TITLE
Illegal string offset 'code'

### ISSUE THREAD

**Issue by informaticosgb** [mercadopago/DEPRECATED-sdk-php#127]
Hola buenas tardes, alguien me ayuda con éste error ? estoy usando las tarjetas de prueba de MP https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/test-cards/
Al momento de crear el pago me lanza este error

![imagen](https://user-images.githubusercontent.com/4468829/43862908-6f553ffe-9b31-11e8-96cf-e09341f6b78e.png)

![imagen](https://user-images.githubusercontent.com/4468829/43862801-2249a34e-9b31-11e8-8529-24702d2b3a6f.png)

**Comment by informaticosgb** [comment]
Haciendo dumps encontré esto 

![imagen](https://user-images.githubusercontent.com/4468829/43864579-6f3a8696-9b36-11e8-8ef5-865010bf4e85.png)

![imagen](https://user-images.githubusercontent.com/4468829/43864608-80aab126-9b36-11e8-98dd-e8d4e1a0439a.png)

**Comment by knifesk** [comment]
aparentemente el problema esta en `$request->installments` que no es numerica... deberías validar todos los parametros antes de pasarselos a ML...  si estas usando lumen no sería `$request->input('installments')`?

**Comment by informaticosgb** [comment]
Gracias Martín por tu respuesta, si tenia que castear la variable a int y funcionó :D

**Comment by knifesk** [comment]
Buenisimo!
