### ISSUE TITLE
Múltiples IPN requests

### ISSUE THREAD

**Issue by nicoworq** [mercadopago/DEPRECATED-sdk-php#128]
Buenas ! Adjunto un extracto de un log de produccion, encargado de recibir las notificaciones IPN. 

Como se puede apreciar, recibí 3 notificaciones en el mismo segundo : 

```
[2018-08-13 11:31:54] production.DEBUG: |||Recibir IPN
[2018-08-13 11:31:54] production.DEBUG: |||Recibir IPN
[2018-08-13 11:31:54] production.DEBUG: |||Recibir IPN
```

La documentación menciona el siguiente esquema:

> Si la aplicación no está disponible o demora en responder, MercadoPago reintentará la notificación mediante el siguiente esquema:
> 
> Reintento a los 5 segundos.
> Reintento a los 45 minutos.
> Reintento a las 6 horas.
> Reintento a los 2 días.
> Reintento a los 4 días.

Pero no menciona nada de que se enviarán varias peticiones simultaneas.  Estaría bueno que se aclare o mencione, ya que particularmente en mi caso tengo que correr un proceso que demora varios segundos cuando recibo las IPN, y recibir varias por segundo me complica bastante las cosas. 

Tuve que emplear una bandera que indique que se recibió una IPN y se está procesando, para ignorar las otras IPN . 

Saludos !

**Comment by knifesk** [comment]
Es indispensable procesar los IPN de forma idempotente.. Jamas confies en
lo que recibis.. siempre verificá si ese ID/Estado de IPN ya se procesó. No
solo con mercadopago, sino con cualquier plataforma de pago

Saludos
