### ISSUE TITLE
TCP connection reset by peer

### ISSUE THREAD

**Issue by alfredogconde** [mercadopago/DEPRECATED-sdk-php#130]
Hace años que tengo implementado MP. 

Sin que yo realice cambios en el codigo empezo a arrojarme este error.
Me paso con la version 0.5.3 y con la version 0.3.2 (la que tuve durante años hasta hoy que detecte el error)

Fatal error: **Uncaught exception 'MercadoPagoException' with message 'TCP connection reset by peer'** in sdk-php-master/lib/mercadopago.php on line 509

**MercadoPagoException: TCP connection reset by peer** in /sdk-php-master/lib/mercadopago.php on line 509

Stack Trace:
MP->create_preference( )	
MP->get_access_token( )	.../mercadopago.php:209
MPRestClient::post( )	.../mercadopago.php:67
MPRestClient::exec( )	.../mercadopago.php:564

El error ocurre al llamar al create_preference, pero tire un var_dump y lo que estoy enviando parece correcto (es el mismo que vengo enviando hace años).

¿Alguien tiene idea que puede ser?

Desde ya muchas gracias

**Comment by jorgepompe** [comment]
a mi me pasa lo mismo, directamente error 500, el error esta al llamar a create_preference
hace unos dias que falla, pudistes solucionarlo?

**Comment by alfredogconde** [comment]
No lo pude solucionar como corresponde. 
Tuve que migrar a otro servidor solo MP. No es la solucion ideal pero me saco del apuro.

**Comment by knifesk** [comment]
Esto suena a un error de routeo que puede ser tanto de ustedes o de MP... en que hostings tienen alojadas sus apps?

**Comment by alfredogconde** [comment]
En Nuthost es donde me falla. 
En Amazon EC2 me funciona correctamente

**Comment by joelibaceta** [comment]
@alfredogconde esto puede ser causado por el protocolo de negociación que estas usando, hace algún tiempo MercadoPago dejo de soportar el protocolo TLS1.0 como es tendencia en la industria, prueba validando eso.
