### ISSUE TITLE
Checkout basico no funciona (Venezuela)

### ISSUE THREAD

**Issue by hdcr1985** [mercadopago/DEPRECATED-sdk-php#131]
Tengo ya bastante tiempo usando el codigo de mercadopago a traves de esta API. Pero ahora no me quiere funcionar y no se si se deba a algun cambio en la libreria.

Cuando creo mi referencia normalmente, el codigo me da error en $preference = $mp->create_preference($preference_data);

Y todo se queda en blanco, intento imprimir $preference pero recibo valor en blanco. Agradecería su ayuda

**Comment by joelibaceta** [comment]
@hdcr1985 aun tenes este problema?
