### ISSUE TITLE
Problemas con los métodos cancel_payment() y refund_payment()

### ISSUE THREAD

**Issue by lucianoghione** [mercadopago/DEPRECATED-sdk-php#133]
Hola,

Estoy utilizando la versión 0.5.3 del SDK PHP, el problema radica en ambos métodos y el error es el mismo, sucede tanto en producción como con usuarios de prueba. 

Cabe destacar que es utilizado con tokens generados de usuarios de MercadoPago a través de una MercadoPago application.

Al intentar llamar estos métodos el error es el siguiente:
MercadoPagoException: Unauthorized use of live credentials - :  - U: U - :  in class.MP.php:534

Desde ya muchísimas gracias,
Saludos

**Comment by joelibaceta** [comment]
@lucianoghione es correcto, el error menciona que para este tipo de operaciones se deben usar access_tokens de largo plazo, no los temporales ( generados a partir de un `client_id` y `client_secret` ).

**Comment by lucianoghione** [comment]
> @lucianoghione es correcto, el error menciona que para este tipo de operaciones se deben usar access_tokens de largo plazo, no los temporales ( generados a partir de un `client_id` y `client_secret` ).

Yo hago esto con los tokens obtenidos de una MercadoPago application,  eso me da un token que vence cada 6 meses, hay alguna manera de que esto funcione con esos tokens?

Saludos
