### ISSUE TITLE
No se envian más notificaciones de suscripción al IPN 

### ISSUE THREAD

**Issue by lucianoghione** [mercadopago/DEPRECATED-sdk-php#136]
Hola, 

Estoy integrado pero cuando una persona se (adhiere/da de baja) el débito automático (pagos recurrentes/suscripciones) ya no se envían las notificaciones a mi IPN. 
Solamente cuando un usuario paga la suscripción si se envía la notificación. Pero no cuando se adhiere/da de baja. 

Esto sucede en entorno de producción y también probe con usuarios de prueba en el entorno de pruebas y pasa lo mismo.

No son problemas en mi código ni nada por el estilo porque hasta hace unas semanas funcionaba perfectamente.

Espero una pronta respuesta,
Saludos.

**Comment by sgarofalo808** [comment]
Buenas, estoy exactamente con el mismo inconveniente.
Luciano tuviste alguna novedad al respecto?

**Comment by lucianoghione** [comment]
> Buenas, estoy exactamente con el mismo inconveniente.
> Luciano tuviste alguna novedad al respecto?

Hola,
Hasta ahora he intentado comunicarme via el formulario de soporte, pero aún no he tenido respuesta, si en algún momento tengo alguna novedad, te aviso.

Saludos

**Comment by knifesk** [comment]
+1

**Comment by asobralr** [comment]
Estoy con el mismo problema. Desde hace poco más de una semana.

**Comment by knifesk** [comment]
@joelibaceta tendrás alguna data?

**Comment by joelibaceta** [comment]
@knifesk @asobralr @lucianoghione efectivamente es un problema detectado y se esta trabajando en resolverlo.

**Comment by sgarofalo808** [comment]
Hola gente, alguna novedad con esto? Hace un mes que esta este problema y me sigue ocurriendo!

**Comment by lucianoghione** [comment]
> Hola gente, alguna novedad con esto? Hace un mes que esta este problema y me sigue ocurriendo!

Hola @sgarofalo808, aún no hay novedades del asunto, realmente espero que se solucione pronto porque es algo bastante grave, te recomiendo como solución provisoria (es lo que yo hice) generarte de alguna manera algún curl request o similar al IPN cada vez que se haga alguna solicitud de suscripción, por ejemplo en tu url de retorno que pusiste en la preferencia. Se que no es una manera elegante de manejarlo y tampoco contempla el caso de que un usuario se de de baja a la suscripción desde su cuenta de Mercado Pago pero es lo que se me ocurrió hacer hasta que solucionen el problema.

@joelibaceta  Alguna novedad?

Saludos!

**Comment by knifesk** [comment]
Yo hice en Postman un request para solventar el problema momentáneamente... 
Lo envio con POST a mi URL de IPN
```json
{
	"resource" : "https://api.mercadolibre.com/preapproval/<id_suscripcion>",
	"topic" : "preapproval"
}
```

**Comment by knifesk** [comment]
El problema es que ahora las suscripciones ni siquiera cambian a estado por cobrar.. tengo una nueva suscripcion en estado "pendiente" que no me figua en el listado de suscripciones y no puedo ver a no ser que ingrese a la URL `https://www.mercadopago.com.ar/subscriptions/detail?id=<id_suscripcion>&plan_id=`

La verdad no me cuadra como pueden demorar más de 22 días en arreglar un problema tan grave

**Comment by lucianoghione** [comment]
> El problema es que ahora las suscripciones ni siquiera cambian a estado por cobrar.. tengo una nueva suscripcion en estado "pendiente" que no me figua en el listado de suscripciones y no puedo ver a no ser que ingrese a la URL `https://www.mercadopago.com.ar/subscriptions/detail?id=<id_suscripcion>&plan_id=`
> 
> La verdad no me cuadra como pueden demorar más de 22 días en arreglar un problema tan grave

@knifesk No se si te sirve de consuelo, pero recién al ver tu mensaje hice una prueba en producción de intentar adherirme al débito con una tarjeta VISA y se puso en estado "Por cobrar". Ante cualquier cambio/nuevo error/novedad, por favor avisen asi nos vamos ayudando entre nosotros.

**Comment by eric-garcia-movile** [comment]
Hola! Me pasa exactamente lo mismo, pero no solo con suscripciones.
También en el basic checkout.
A ustedes solo les pasa con las notificaciones de suscripciones?

**Comment by joelibaceta** [comment]
Este es un canal destinado a reportar incidencias sobre el SDK Legacy de PHP, para consultas técnicas deben dirigirse al canal oficial de soporte http://www.mercadopago.com.ar/developers/es/support procedo a cerrar el issue ya que lo reportado corresponde a un bug en otro componente.

**Comment by sgarofalo808** [comment]
@joelibaceta Disculpa, el otro dia lo marcaste como bug, y ahora es una consulta tecnica?
Hay multiples usuarios reportando lo mismo, es obvio que rompieron algo que venia andando bien del lado de MercadoPago

**Comment by joelibaceta** [comment]
@sgarofalo808 efectivamente, un issue se marca como bug cuando el equipo puede reproducir el error, posteriormente se identifica si corresponde a un problema del SDK ( Se envían parámetros incorrectos, hay un bug de código u otro error ), en este caso el proceso de diagnostico tuvo como resultado que este issue no esta relacionado a un problema del SDK alojado en este repositorio sino en el motor de notificaciones por lo cual pierde la naturaleza de bug.

Por eso sugerimos comunicarse con el canal apropiado en el cual se están gestionando los casos relacionados a este problema, este canal esta destinado únicamente a la discusión sobre el SDK de PHP  legacy

**Comment by sgarofalo808** [comment]
Alguien sabe si updatear a dx-php (https://github.com/mercadopago/dx-php) arregla el problema?

Tengo 0 fe en contactar a soporte, tardan una semana en contestar y hace dias me dijeron que este problema estaba resuelto, que claramente no lo esta.

EDIT: DX-PHP esta con build error, un lujo mercadopago.

![image](https://user-images.githubusercontent.com/8806890/48272820-4b671a00-e41e-11e8-900e-40eca08fd260.png)

**Comment by joelibaceta** [comment]
@sgarofalo808 Como comente en la parte superior, para este caso especifico el bug de notificaciones no esta relacionado a un incidente en el SDK sino a un bug del motor de notificaciones interno, para preguntas de problemas de este tipo y/o problemas genéricas que escapan al scope de los sdks esta el canal de soporte.
