### ISSUE TITLE
Consulta codigos de respuesta IPN

### ISSUE THREAD

**Issue by lucianoghione** [mercadopago/DEPRECATED-sdk-php#138]
Hola, necesito saber que http_response_code hay que enviar como respuesta en caso de que haya, por ejemplo, un error de conexión o similar en mi base de datos, para que Mercado Pago me vuelva a enviar la notificación.

Cito lo que dice en la documentación:
> Cuando recibas una notificación en tu plataforma, MercadoPago espera una respuesta para validar que la recibiste correctamente. Para esto, debes devolver un HTTP STATUS 200 (OK) ó 201 (CREATED).
Si la aplicación no está disponible o demora en responder, MercadoPago reintentará la notificación mediante el siguiente esquema:
Reintento a los 5 segundos.
Reintento a los 45 minutos.
Reintento a las 6 horas.
Reintento a los 2 días.
Reintento a los 4 días.

Se que cuando estuvo todo ok hay que enviar el 201 o 200, pero no encontré información al respecto de que código enviar cuando ocurre algún inconveniente al procesar la notificación.

Saludos!

**Comment by knifesk** [comment]
Deberías asegurarte que tu código responda con 500 si hay un error.. ojo, a veces cuando PHP tira error fatal el código de respuesta es 200 a pesar del error... 

Si tu server está bloqueado, down o algo por el estilo no vas a poder controlarlo.. pero siempre y cuando la respuesta no sea 200 ML debería intentar enviar el ipn nuevamente...  aunque tené en cuenta que está la #136

**Comment by lucianoghione** [comment]
> Deberías asegurarte que tu código responda con 500 si hay un error.. ojo, a veces cuando PHP tira error fatal el código de respuesta es 200 a pesar del error...
> 
> Si tu server está bloqueado, down o algo por el estilo no vas a poder controlarlo.. pero siempre y cuando la respuesta no sea 200 ML debería intentar enviar el ipn nuevamente... aunque tené en cuenta que está la #136

Ah buenísimo, sisi, yo mismo cree ese hilo jaja.
Mil gracias @knifesk !
