### ISSUE TITLE
Pago Recurrente / no podremos procesar tus pagos con esta tarjeta 

### ISSUE THREAD

**Issue by rockscripts** [mercadopago/DEPRECATED-sdk-php#139]
Hola, tengo problemas probando pago recurrente para Argentina y el payer email es de prueba generado como lo indican al igual que la tarjeta de prueba
Por favor ver capturas.
![error](https://user-images.githubusercontent.com/20305057/47960410-502d6780-dff3-11e8-927d-c85824253fc8.png)
![fill-card](https://user-images.githubusercontent.com/20305057/47960411-50c5fe00-dff3-11e8-9eea-02193c065865.png)

```
$data = array(
			'order_frequency' => 1,
			'order_frequency_type' => 'months',
			'currency_code' => "ARS",
			'customer_email' => 'test_user_88350946@testuser.com',
			'order_reference' => 'REF-2424',
			'amount' => 5000
		);

		$preapproval_data = new \MercadoPago\Preapproval();
		$preapproval_data->payer_email = $data['customer_email'];
		
		$preapproval_data->back_url = "https://mysite.com";
		$preapproval_data->reason = "Monthly subscription to premium package";
		$unixTimestamp = time();
		$start_date = date("Y-m-dTH:i:s", $unixTimestamp);
		$end_date = date($unixTimestamp, strtotime('+1 years'));
		$end_date= date("Y-m-dTH:i:s", $end_date);
		$start_date = str_replace("UTC","T",$start_date);
		$end_date = str_replace("UTC","T",$end_date);
		$preapproval_data->auto_recurring = array( 
			"frequency" => 1,
			"frequency_type" => "months",
				"transaction_amount" => 60,
				"currency_id" => "ARS",
				"start_date" => $start_date.".778-03:00",
			  "end_date" => $end_date.".778-03:00"
		  );
	  $preapproval_data->save();
	  $url = $preapproval_data->init_point;
          return $url; 
```

**Comment by joelibaceta** [comment]
@rockscripts Si puedes iniciar el Checkout de suscripciones a partir del `init_point` el flujo del SDK esta finalizando correctamente, me parece mas un error o problema con el checkout de suscripciones, para este tipo de consultas puedes dirigirte al canal de soporte tecnico oficial https://www.mercadopago.com.ar/developers/es/support

Este canal tiene como fin reportar bugs o sugerencias sobre el sdk alojado en este proyecto.
