### ISSUE TITLE
"Unit_Price" Variable

### ISSUE THREAD

**Issue by j34nt** [mercadopago/DEPRECATED-sdk-php#14]
on the platform we want to implement the sdk MercadoPago, array "UNIT_PRICE" must be a variable, not a fixed amount per product. is this possible?

**Comment by cappells** [comment]
Any news on this matter? If this is a checkout button should be able to support a PHP variable.

**Comment by alvijunior** [comment]
Hello,
In the array, change the price value to  floatval($yourPriceValue). This change solved for me. 

Example: 

print_r ($preference_data = array(
    "items" => array(
        array(
            "id" => "$row[codigoPedido]",
            "title" => "Pedido $row[codigoPedido] ",
            "currency_id" => "BRL",
            "category_id" => "Category",
            "unit_price" => floatval($totalPed),
            "quantity" => 1  
        )
    )
) );

**Comment by timersys** [comment]
Thanks, really odd how long this ticket been open. I was trying to format_number but wasn't working
    floatval(number_format((float)$_POST['cuanto'], 2, '.', ''))
Now it is, with floatval
