### ISSUE TITLE
implemente el sdk en modo producción y falla cuando confirman el pago

### ISSUE THREAD

**Issue by tomy914** [mercadopago/DEPRECATED-sdk-php#140]
![error-mercado-pago](https://user-images.githubusercontent.com/11417708/48177360-e4991200-e2f2-11e8-93ac-188e8586a65e.jpg)

**Comment by joelibaceta** [comment]
Podrías ampliar la consulta sobre el SDK Legacy, como el snippet de código usado, para tratar de diagnosticar si corresponde a un problema de este proyecto.

**Comment by tomy914** [comment]
Hola Joel queres que pegue el código en el repositorio o por email. En
teoría el código está bien porque en modo sandbox y con tarjetas de prueba
anda todo bien, cuando lo paso a producción configuro sandbox=falso y pongo
el token de producción me genera el código del checkout bien, me crea el
init-point. Ingreso al formulario de mercado pago y te toma los datos,
válida la información y llega al último paso, pagar.... Y ahí salta el
error de la imagen que adjunte. Al menos hasta ese día pasaba eso. Voy a
probar otra vez. Y probé hacer un botón con la app y de la mandé a mí
cliente para que pague por ahi con la misma tarjeta y se lo tomó bien sin
problema.
Además hay un tema con la web que configuras para notificaciones.
Por un lado te dice que recibis dos campos, tipo e id ( merchant o payment)
pero al hacer el botón de pago vía app la notificación informa los datos
que provee el checkout. Y collection-id, status etc.

**Comment by tomy914** [comment]
Hola te cuento que descubrí el error o al menos descubrí en qué parte del
código falla, ante todo ya les escribí al soporte para decirles que algo en
la validación fallo porque si hay un error no debería generar el init_point
en mí código el error está en la parte de envío, lo tenía configurado como
custom para evitar que elijan mercado envío ya que no lo dispongo en la
zona y comenté esa zona de código y el pago entro de manera exitosa, luego
les pego el código y si descubro el error les aviso, ya que es en modo de
producción que falla no en modo sandbox.
