### ISSUE TITLE
Problema con busqueda de pagos in proceso

### ISSUE THREAD

**Issue by aariza-argentina** [mercadopago/DEPRECATED-sdk-php#141]
**Describe the bug**
Al hacer una busqueda de pagos, desde hace unos dias los recurring_payment que estan en [status] => in_process devuelven los datos del payer incompleto (sin el mail) por ejemplo

   [payer] => Array
        (
            [entity_type] => 
            [identification] => Array
                (
                )
            [phone] => Array
                (
                )
            [operator_id] => 
            [last_name] => 
            [id] => [saque el numero pero este campo viene ok]
            [type] => registered
            [first_name] => 
            [email] => 
        )

No asi los pagos que estan approved

Puede ser que haya cambiado algo?

**To Reproduce**
Depende de los pagos

**Expected behavior**
Que vengan todos los datos del payer

Muchas Gracias!

**Comment by joelibaceta** [comment]
Efectivamente se envia unicamente el `id`, con esto puedes consultar la informacion del payer usando el api de `/users`

**Comment by aariza-argentina** [comment]
El problema es que la api /users/[id] no trae el email tampoco, puede ser?

**Comment by joelibaceta** [comment]
Efectivamente, ya que se considera informacion privada, entiendo que algunos pagos si proveen informacion de payer más completa.

@aariza-argentina si, podrias escribir al canal de soporte ?https://www.mercadopago.com.ar/developers/es/support para que puedan solicitar los ids de pagos y revisar el caso en particular, es probable que ciertos tipos de pagos ( **guess** ) sin login de mercado pago no tengan un mail asociado.
