### ISSUE TITLE
Exception handling response "Payment not found"

### ISSUE THREAD

**Issue by franco-testagrossa** [mercadopago/DEPRECATED-sdk-php#147]
Estoy teniendo un error al momento en que la SDK (version = “0.5.3”) llama al endpoint: 
  ```GET /v1/payments/$payment_id?access_token=$access_token```

Linea donde salta la excepción:
    https://github.com/mercadopago/sdk-php/blob/master/lib/mercadopago.php#L526

`ErrorException`: Uncaught exception ‘ErrorException’ with message ’Illegal string offset ‘code’'

Haciendo la llamada que realizaba la SDK manualmente, la respuesta que recibí fue:

```
{
    "message": "Payment not found",
    "error": "not_found",
    "status": 404,
    "cause": [
        {
            "code": 2000,
            "description": "Payment not found",
            "data": null
        }
    ]
}
```

Por lo que entiendo:
Internamente falla al momento de procesar un $response[‘status’] >= 400
cuando el $response.cause es un array e intenta recuperar el atributo code del response.
(puede q esto requira validaciones de `isset` para ver si existe el campo en el array)

**Comment by joelibaceta** [comment]
@franco-testagrossa gracias por el reporte, lo reviso.

**Comment by joelibaceta** [comment]
@franco-testagrossa según pudimos revisar, desde la version **7.1** de PHP se cambia el comportamiento cuando se realiza una asignación mediante un indice a una variable que es inicialmente un String ( _Esperando la inferencia de tipos_ ) lo cual genera una inconsistencia en la evaluación del método `is_array` y es tratado como un String generando el error `Illegal string offset ‘code’` al tratar como un `String` a un `Array`. 

```php
$a = '';
$a[10] = 'foo';
is_array($a) // false
```

Vamos a evaluar alternativas para controlar este escenario

http://php.net/manual/en/migration71.incompatible.php#120845

**Comment by joelibaceta** [comment]
Fixed in https://github.com/mercadopago/sdk-php/commit/cdc0680cb4702f86b6df60fa58186e16d4a32147
