### ISSUE TITLE
Pagos rechazados en el primer intento, pero cobrado satisfactoriamente en los siguientes. IPN

### ISSUE THREAD

**Issue by vousys** [mercadopago/DEPRECATED-sdk-php#149]
Chicos buen dia, nos esta pasando en diferentes tiendas donde tenemos integrado el checkout basico que 
- El cliente abona y por algun motivo en el primer intento de pago, le rechaza la transaccion.
- Intenta con otra tarjeta o como sea y lo abona.

Cuando hacemos el search_payment, del pago asociado nos devuelve:

```
[shipping_amount] => 0
    [sponsor_id] => 
    [statement_descriptor] => MERCADOPAGO
    [status] => rejected
    [status_detail] => cc_rejected_other_reason
    [store_id] => 
    [taxes_amount] => 0

```
Sin embargo, nos llega por mail la notificacion de que se recibio el pago , el cual se corrobora en la cuenta de MP y efectivamente está cobrado.

Nos genera muchos problemas, ya que los IPN que estan corriendo solos, detectan el pago como rechazado en lugar de cobrado y no se les libera las ordenes a la gente, de hecho hasta inician mediaciones para que se les devuelva el dinero.

**Comment by joelibaceta** [comment]
@vousys este no es un canal de soporte general, sino esta destinado para la discusión sobre bugs o nuevos features para el SDK legacy de MercadoPago, el canal oficial de soporte general para desarrolladores es : http://mercadopago.com.ar/developers/es/support/

**Comment by vousys** [comment]
@joelibaceta , no pedí soporte.
Simplemente reporte que el el servicio devuelve que los pagos fueron
rechazados, cuando el estado final del pago es aprobado. Eso para mí es un
bug del servicio, si lo quieren ignorar no hay problema, pero como
desarrolladora lo considero un bug.

**Comment by joelibaceta** [comment]
@vousys cómo comente este canal no esta destinado a la discusión de bugs generales de los APIs, Productos o Servicios de MercadoPago, sino a la discusión técnica de bugs de este SDK en especifico.
El equipo de soporte para desarrolladores dispone de mejores herramientas para reportar bugs internos o dar seguimiento sobre incidentes de los APIs el flujo de las aplicaciones internas.
