### ISSUE TITLE
Problema con notificaciones.

### ISSUE THREAD

**Issue by Mikee93** [mercadopago/DEPRECATED-sdk-php#150]
Estoy implementando mercadopago en mi próximo sitio, pero estoy teniendo un problema, al momento de crear el proceso de checkout y realizar el pago, se me envía correctamente la notificación a la url colocada en "notification_url", el problema es que se envía 3 veces la misma notificación, alguna solución? 
Estoy basandome en este ejemplo:
`https://github.com/mercadopago/sdk-php/blob/master/examples/checkout-buttons/basic-preference/button_full.php`

**Comment by joelibaceta** [comment]
@Mikee93 esto es normal, las notificaciones pueden llegar multiples veces para asegurar su entrega, por este emotivo es importante disponer de un servicio idempotente o validar si es el pago ya fue procesado correctamente.

Adicionalmente te comento que este no es un canal de soporte general sobre productos o servicios de MercadoPago sino unicamente bugs o features del SDK legacy para PHP.  te comparto el canal de soporte oficial [http://mercadopago.com.ar/developers/es/support/](http://mercadopago.com.ar/developers/es/support/)
