### ISSUE TITLE
'ErrorException' with message 'Undefined variable: causes

### ISSUE THREAD

**Issue by franco-testagrossa** [mercadopago/DEPRECATED-sdk-php#151]
Debido al ISSUE: https://github.com/mercadopago/sdk-php/issues/147
se realizó un FIX: https://github.com/mercadopago/sdk-php/commit/cdc0680cb4702f86b6df60fa58186e16d4a32147
que esta causando nuevos problemas al momento en que la SDK llama a los endpoint:
[GET] /v1/payments/$payment_id
[GET] /merchant_orders/$merchant_order_id

Error message
ErrorException: Uncaught exception 'ErrorException' with message 'Undefined variable: causes

Linea donde salta la excepción:
https://github.com/mercadopago/sdk-php/blob/master/lib/mercadopago.php#L521

Evidentemente la variable no esta en scope.

**Comment by joelibaceta** [comment]
@franco-testagrossa is correct, my mistake, solved in https://github.com/mercadopago/sdk-php/commit/6a3348fac44ba59d716687890086b6e8f84e30ba
