### ISSUE TITLE
No funciona más en Brasil | Doesn't Work anymore in Brazil

### ISSUE THREAD

**Issue by zeehkaev** [mercadopago/DEPRECATED-sdk-php#154]
Al usar para el checkout con redireccionamiento, todas las ventas tienen error en el momento de seleccionar la forma de pago.
"Tuvimos un problema, vuelva a intentarlo".

No hay número de error, código ni advertencia, sólo un error amarillo con esta advertencia.

When using for checkout with redirection, all sales have error at the time of selecting the form of payment.
"We had a problem try again".

There is no error number, no code, no warning, only a yellow error with this warning.
![Screenshot_1](https://user-images.githubusercontent.com/49571323/56063971-2701c780-5d47-11e9-962a-38454494b836.png)

**Comment by joelibaceta** [comment]
@zeehkaev este canal no esta destinado al soporte genérico sobre productos o servicios de MercadoPago, para ello te sugiero usar el canal de soporte técnico oficial https://www.mercadopago.com.br/developers/pt/support/ , este medio tiene como fin discutir bugs asociados al SDK legacy de MercadoPago.
