### ISSUE TITLE
No funciona desde el viernes en Brasil

### ISSUE THREAD

**Issue by zeehkaev** [mercadopago/DEPRECATED-sdk-php#155]
Al usar este SDK para el checkout con redireccionamiento, todas las ventas tienen error en el momento de seleccionar la forma de pago.
"Tuvimos un problema, vuelva a intentarlo".

el sdk funcionaba normalmente hasta el viernes pasado, después hubo algún cambio en los servidores de MercadoPago

Algunos adm cerrado aquí pensando que no me refiero a sdk pero me refiero. El SDK está con errores en Brasil al menos desde el viernes pasado.
![56063971-2701c780-5d47-11e9-962a-38454494b836 (1)](https://user-images.githubusercontent.com/49571323/56108450-689a9a00-5f22-11e9-9fdc-092cb496604c.png)

No hay número de error, código ni advertencia, sólo un error amarillo con esta advertencia.

**Comment by joelibaceta** [comment]
Este SDK tiene como finalidad generar el link del botón de pago una vez se inicia el flujo de pagos del checkout este escapa al contexto del SDK y corresponde a otro producto, web checkout, para soporte sobre productos o servicios de MercadoPago te sugiero escribir al canal de soporte oficial.

Este canal esta destinado únicamente a la discusión sobre bugs o ideas para el código alojado en este repositorio.
