### ISSUE TITLE
Error converting access token

### ISSUE THREAD

**Issue by clubdesarrolladores** [mercadopago/DEPRECATED-sdk-php#20]
A que se debe este error?
En desarrollo funciona, en producción obtenemos este error.
Es una dependencia no cumplida en el servidor?
Me pueden aclarar esto?

Para generar el token del pedido, MercadoPago intenta acceder al sitio que envia la petición?

**Comment by eleiva** [comment]
Hola Club!

No creo que sea una dependencia no cumplida.
El siguiente es el codigo por el cual pide el token:

```
public function get_access_token() {
        $app_client_values = $this->build_query(array(
            'client_id' => $this->client_id,
            'client_secret' => $this->client_secret,
            'grant_type' => 'client_credentials'
                ));

        $access_data = MPRestClient::post("/oauth/token", $app_client_values, "application/x-www-form-urlencoded");

        $this->access_data = $access_data['response'];

        return $this->access_data['access_token'];
    }
```

Ojo, no soy de Mercadolibre. 
Al parecer tardan un poco en contestar.

Saludos!
