### ISSUE TITLE
PHP-SDK not set  attributes "external_reference" and "order_id"

### ISSUE THREAD

**Issue by silascardoso** [mercadopago/DEPRECATED-sdk-php#21]
Hi, 

I'm trying to set the attributes: "external_reference"  and "order_id", but their values ​​are always null: 

My code: 

$preference_data = array(
    "external_reference" => "123",
    "order_id" => "456",
    "items" => array(
       array(
           "title" => "Atari 2600",
           "quantity" => 1,
           "currency_id" => "ARS",
           "unit_price" => 150.00
       )
    )
);

$preference = $mp->create_preference($preference_data);

<a href="<?php echo $preference['response']['init_point']; ?>" class="orange-rn-m"  name="MP-Checkout">Pay</a>

**Comment by matiasgordon** [comment]
Hi, It should be:

$preference_data = array(
    "items" => array(
        array(
            "id" => "456",
            "title" => "Atari 2600",
            "currency_id" => "ARS",
            "quantity" => 1,
            "unit_price" => 150.00
        )
    ),
    "external_reference" => "123",
);

$preference = $mp->create_preference($preference_data);

Regards!
