### ISSUE TITLE
Create release versions to use with composer

### ISSUE THREAD

**Issue by sebathi** [mercadopago/DEPRECATED-sdk-php#23]
It will make your package to be imported by composer with more control than dev-stable.

**Comment by sebathi** [comment]
Nobody is maintaining this repository isn't it?

**Comment by mariano** [comment]
@sebathi I believe this is done https://packagist.org/packages/mercadopago/sdk

**Comment by sebathi** [comment]
This is published in packagist/composer, but no version is added. If you do changes on your dev branch, it will pull your changes on our projects and it's very likely that you will not notice the change and update. Also when installing a new environment.

**Comment by danielcosta** [comment]
Yes, please maintain versions of your releases.

"dev-master" is not exactly the prefered version of a package to choose when a big project goes live.

Check this link for reference: https://getcomposer.org/doc/02-libraries.md#specifying-the-version

**Comment by sebathi** [comment]
Does someone readthis issue??

**Comment by hcasatti** [comment]
Done: https://packagist.org/packages/mercadopago/sdk

**Comment by sebathi** [comment]
Thank you! This is great! Now we can start using with our project and composer!!
