### ISSUE TITLE
El codigo no permite crear preferencias en modo Sandbox

### ISSUE THREAD

**Issue by asmerkin** [mercadopago/DEPRECATED-sdk-php#24]
```
public function create_preference($preference) {
    $access_token = $this->get_access_token();

    $preference_result = MPRestClient::post("/checkout/preferences?access_token=" . $access_token, $preference);
    return $preference_result;
}
```

**Comment by matiasgordon** [comment]
Hola Asmerkin,
Puedes ver en la documentación de Sandbox cómo utilizar el SDK en esta modalidad.
http://developers.mercadopago.com/sandbox
Saludos,

**Comment by asmerkin** [comment]
Genial, y el tema de los refunds se pueden testear en sandbox? No encontré la forma. 

Gracias!

**Comment by matiasgordon** [comment]
API PUT
https://api.mercadolibre.com/sandbox/collections/ID_DE_PAGO/status?access_token=TU_ACCESS_TOKEN

 {"status": ":refunded", "status_detail": ":refunded"}

Saludos,

**Comment by asmerkin** [comment]
Ah, yo estaba usando el sdk para php. Me recomendás que haga un call
directo?

Gracias!

2014-09-16 15:04 GMT-03:00 Matias Gordon notifications@github.com:

> API PUT
> 
> https://api.mercadolibre.com/sandbox/collections/ID_DE_PAGO/status?access_token=TU_ACCESS_TOKEN
> 
> {"status": ":refunded", "status_detail": ":refunded"}
> 
> Saludos,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mercadopago/sdk-php/issues/24#issuecomment-55786323.

## 

Andrés Smerkin
http://www.andressmerkin.com.ar

**Comment by matiasgordon** [comment]
El SDK no esta preparado para refund en sandbox. Podes agregarlo modificando la funcion refund_payment:

``` php
public function refund_payment($id) {
        $access_token = $this->get_access_token();

        $uri_prefix = $this->sandbox ? "/sandbox" : "";

        $refund_status = array(
            "status" => "refunded"
        );

        $response = MPRestClient::put($uri_prefix."/collections/" . $id . "?access_token=" . $access_token, $refund_status);
        return $response;
    }
```

En el archivo donde llames a la funcion refund_payment agrega:

``` php
 $mp->sandbox_mode(TRUE);
```

Saludos.

**Comment by asmerkin** [comment]
Si lo hice pero no funcionó. No se pq
Sent using CloudMagic
On mar, sep 16, 2014 at 3:23 PM, Matias Gordon notifications@github.com wrote:El SDK no esta preparado para refund en sandbox. Podes agregarlo modificando la funcion refund_payment:

public function refund_payment($id) {
        $access_token = $this->get_access_token();

```
    $uri_prefix = $this->sandbox ? "/sandbox" : "";

    $refund_status = array(
        "status" => "refunded"
    );

    $response = MPRestClient::put($uri_prefix."/collections/" . $id . "?access_token=" . $access_token, $refund_status);
    return $response;
}
```

En el archivo donde llames a la funcion refund_payment agrega:

 $mp->sandbox_mode(TRUE);

Saludos.

**Comment by knifesk** [comment]
Se que quizas a vos ya no te haga falta, pero yo probé directamente haciendo un PUT a la api de sandbox y no me funcionó hasta que cambie el content-type a `application/json`
