### ISSUE TITLE
Not getting the access token - No recibo el access token

### ISSUE THREAD

**Issue by areyalp** [mercadopago/DEPRECATED-sdk-php#25]
ENGLISH:

Hi, i was trying just to receive the access token but i couldn't, I tried this code:

$mp = new MP("MY_CLIENT_ID", "MY_SECRET");
$token = $mp->get_access_token();
var_dump($token);

the $access_data variable inside the get_access_token() method has this after the POST call:

access_data
array(2) { ["status"]=> int(0) ["response"]=> NULL }

and my $token variable has NULL value after the call to $mp->get_access_token()

ESPAÑOL:

Hola, estuve tratando de recibir el access token pero no pude, yo intente con este codigo:

$mp = new MP("MY_CLIENT_ID", "MY_SECRET");
$token = $mp->get_access_token();
var_dump($token);

la variable access_data que esta dentro del metodo get_access_token() contiene lo siguiente luego de la llamada POST:

access_data
array(2) { ["status"]=> int(0) ["response"]=> NULL }

y mi variable $token tiene valor NULL luego de la llamada a $mp->get_access_token()

**Comment by mgscreativa** [comment]
Hi, I'm having the same problem as from yesterday!

Getting
access_data
array(2) { ["status"]=> int(0) ["response"]=> NULL }

I'm using MP SDK v0.2.4 with sandbox mode activated

Please advise!

**Comment by hcasatti** [comment]
Could you upgrade to version 0.2.5 and test again ?

_Horacio E. Casatti_
Sr. Software Engineer - La Punta - San Luis
horacio.casatti@mercadolibre.com
Int. 1648

**Comment by mgscreativa** [comment]
Yep, upgraded to 0.2.5 and works!
