### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Exception' with message 'not_found'

### ISSUE THREAD

**Issue by Sheraf1** [mercadopago/DEPRECATED-sdk-php#28]
I'm getting this exception when i create a subscription button.

response from the API:
Array
(
    [message] => not_found
)

**Comment by matiasgordon** [comment]
Hi @Sheraf1 ! Please let me know how are you creating the preapproval.

Regards,

Matías Gordon | IT Analyst - MercadoPago
