### ISSUE TITLE
Never getting "authorized_payment" for subscription

### ISSUE THREAD

**Issue by Sheraf1** [mercadopago/DEPRECATED-sdk-php#29]
the IPN never send me the "authorized_payment".
I'm getting the payment:
[operation_type] => recurring_payment
some minutes after the subscription, but i never get anything else telling me that the buyer has subscribed.

**Comment by sebagun** [comment]
You'll receive the data about the new subscription under the "preapproval" topic. See this link for more information: http://developers.mercadopago.com/documentacion/notificaciones-de-pago#notification-url
(Recurring-Payments tab)
