### ISSUE TITLE
IPN SSL ignorada por servidores de MercadoPago

### ISSUE THREAD

**Issue by oosswwaalldd** [mercadopago/DEPRECATED-sdk-php#30]
Buenas tardes, 

hace un par de semanas cambiamos toda nuestra app en la web a https (SSL), una vez realizado este cambio, actualizamos la url en nuestro perfil de MercadoPago para que la IPN pasara de http a https, a partir de ese momento ninguna IPN llegó a nuestro server, preocupados, excluímos la ruta de la IPN para que trabajara solamente con http (sin SSL) y volvió a funcionar. La pregunta: por qué es ignorada la url con SSL de las IPN? hay que hacer algo adicional más allá de cambiar en nuestro perfil http por https?

Atentos a sus comentarios

Saludos

**Comment by sebagun** [comment]
Hola Oswald. cómo estás? Te comento que la IPN soporta ambos esquemas (HTTP y HTTPS) transparentemente. Pasanos por privado al mail developers@mercadopago.com tu usuario y ambas URLs para ver qué pudo haber ocurrido.

Saludos
