### ISSUE TITLE
api.mercadopago.com no funciona.

### ISSUE THREAD

**Issue by alejoasotelo** [mercadopago/DEPRECATED-sdk-php#32]
Hola, 

el error es basicamente que REST en mercadopago.com no funciona. https://api.mercadopago.com/sites
El dominio correcto seria api.mercadolibre.com, tal vez estan por implementarlo, pero por el momento devuelve un json vacio. 
Peticion corrrecta: https://api.mercadolibre.com/sites
Peticion erronea: https://api.mercadopago.com/sites

El archivo en cuestion en lib/mercadopago.php, linea 332.

![mercadopago](https://cloud.githubusercontent.com/assets/1103289/6376806/043abcb2-bcff-11e4-8a61-3807c4bfd34f.jpg)

![mercadolibre](https://cloud.githubusercontent.com/assets/1103289/6376791/f82b252e-bcfe-11e4-9cf8-5c6846fe1520.jpg)

**Comment by sebagun** [comment]
Esa API (sites) no está disponible a través de api.mercadopago.com
¿Para qué la necesitarías?

**Comment by alejoasotelo** [comment]
Uso el modulo para prestashop y dejó de funcionar cuando actualice su libreria.
Cambie el dominio porque vi que no funcionaba y empezo a funcionar como siempre.
Usa "/sites/country/payment_methods", "/sites" y "/item_categories".

Modulo Prestashop: https://github.com/mercadopago/cart-prestashop/tree/master/v1.5.3%20-%201.6.x/mercadopago

**Comment by sebagun** [comment]
Ya veo, pero la librería del carrito en sí aún no fue modificada y mantiene el uso del dominio api.mercadolibre.com:
https://github.com/mercadopago/cart-prestashop/blob/master/v1.5.3%20-%201.6.x/mercadopago/includes/mercadopago.php#L243

Por lo que no debería fallar, no deberías sobrescribirla.

De momento deberías mantener la versión de la librería que se ofrece aún con el carrito, hasta que pongamos estas APIs disponibles en el nuevo dominio.

**Comment by alejoasotelo** [comment]
Claro, por que esta desactualizado. Tengo la libreria de ustedes acutalizada con ese mismo modulo funcionando perfecto. Es mas, al modulo le tuve que hacer algunas modificaciones extras para corregir errores. Cierro el tema porque va a prestar a confusion.
saludos y gracias sebagun!

**Comment by sebagun** [comment]
La API en cuestión ya está disponible bajo el domain https://api.mercadopago.com/sites

De todos modos no te recomiendo que modifiques el comportamiento del carrito ni del SDK que este contiene. Próximamente estaremos publicando versiones actualizadas de los carritos, que reflejen los cambios realizados en los SDKs.

Saludos
