### ISSUE TITLE
Interoperabilidad entre plataformas

### ISSUE THREAD

**Issue by joarobles** [mercadopago/DEPRECATED-sdk-php#35]
Sugiero implementen PSR-4 para brindar mejor interoperabilidad entre plataformas y brindar soporte a autoload

**Comment by joelibaceta** [comment]
@joarobles gracias por la sugerencia, te invito a revisar la nueva versión del SDK https://github.com/mercadopago/dx-php

**Comment by joarobles** [comment]
Genial! Igual creo que hace 3 años lo resolví con un fork
