### ISSUE TITLE
Create a preference with multiple items

### ISSUE THREAD

**Issue by silascardoso** [mercadopago/DEPRECATED-sdk-php#40]
Create a preference with multiple items

**Comment by smarbos** [comment]
Nothing?

**Comment by sebagun** [comment]
Check out the documentation here: http://developers.mercadopago.com/documentation/receive-payments

and here: http://developers.mercadopago.com/documentation/api/preferences

Best regards

**Comment by silascardoso** [comment]
Hi,thank you for explanattion.

I know how to do, the problem is that the items are not saved in
MercadoPago database, when I check the payment, only the first item is
displayed.

2015-06-15 16:59 GMT-03:00 Sebastián Gun notifications@github.com:

**Comment by sebagun** [comment]
@silascardoso, the items are saved. But only the first item in the list is shown in the left column of the checkout. No matter how many items you send, the checkout will charge the user for the total amount (sum of each item amount), although only one item is shown.
If you want to improve the message, try to arrange a better description in the first item.

Regards

**Comment by fnotti** [comment]
It's "Ok" to send 1 line item with all the amount and a general description?...

Regerds.-

**Comment by tincho** [comment]
Hi! Same here... what's the point of including all items with picture and description in the preference if only the first will be shown? Confuses the user. There's no way to change this behavior? Thanks!

**Comment by babblo** [comment]
@tincho thats exactly what I was thinking. BTW, any news about this?

**Comment by davidnarea** [comment]
any news about this "issue"?

**Comment by NahuBocco** [comment]
Any news?

**Comment by tinchoforever** [comment]
zzzzz

**Comment by babblo** [comment]
C'mon! Why aren't you going to fix this? It's important for users to see details about what they are buying and not a single line

**Comment by joelibaceta** [comment]
@babblo agree, but this feature is not in the medium-term roadmap.
