### ISSUE TITLE
error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by oosswwaalldd** [mercadopago/DEPRECATED-sdk-php#41]
Hola Amigos, 

Uso la version 0.3.0 de la lib php de mercadopago, el dia de hoy, luego de siempre funcionar bien me aparecio este error, reportado por un cliente al intentar pagar: 

"error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure"

Les doy detalles: el error se presenta al intentar generar un boton con opciones de pago personalizadas y el error me lo da exactamente en el retorno de la variable $api_result

```
    private static function exec($method, $uri, $data, $content_type) {
        $connect = self::get_connect($uri, $method, $content_type);
        if ($data) {
            self::set_data($connect, $data, $content_type);
        }

        $api_result = curl_exec($connect);
        $api_http_code = curl_getinfo($connect, CURLINFO_HTTP_CODE);

        if ($api_result === FALSE) {
            throw new Exception (curl_error ($connect));
        }

       $response = array(
            "status" => $api_http_code,
            "response" => json_decode($api_result, true)
        );

        if ($response['status'] >= 400) {
            throw new Exception ($response['response']['message'], $response['status']);
        }

       curl_close($connect);

        return $response;
    }
```

Toda la ayuda que me puedan prestar en este caso sera agradecida

Saludos

**Comment by hcasatti** [comment]
Podrias probar de actualizar a la ultima version (0.3.2) y confirmarme si
sigue pasando ?
Slds...

_Horacio E. Casatti_
Sr. Software Engineer - La Punta - San Luis
horacio.casatti@mercadolibre.com
Int. 1648

2015-04-28 12:13 GMT-03:00 Oswald Reyes notifications@github.com:

**Comment by oosswwaalldd** [comment]
Gracias @hcasatti, si sirvió la actualización de la librería a la 0.3.2 se arregló el problema de handshake. Un millón de gracias.

**Comment by hcasatti** [comment]
Buenisimo...

**Comment by edinsoncs** [comment]
Hola hcasatti una pregunta para agregar las nuevas actualizaciones de mercadopago a opencart esta disponible su modulo?

**Comment by sebagun** [comment]
@ockang Bajá e instalá la última versión del módulo en https://github.com/mercadopago/cart-opencart

**Comment by edinsoncs** [comment]
agregue ello pero no muestra los países http://prntscr.com/73jg66

**Comment by edinsoncs** [comment]
ahora sale esto http://prntscr.com/73jo7x

**Comment by ockang** [comment]
Hola necesito resolver tengo ese problema

**Comment by edinsoncs** [comment]
MercadoPago fails to connecet, and debug mode is on !!.
Check the erros below and for security reasons turn it off after solve the problem:
Error: 0
