### ISSUE TITLE
Parámetros expires y expiration_date_to

### ISSUE THREAD

**Issue by barbanet** [mercadopago/DEPRECATED-sdk-php#44]
Al momento de crear un botón de compra, he intentado enviar los parámetros expires con valor true y expiration_date_to con el siguiente formato: https://github.com/mercadopago/cart-magento/blob/master/v1.6.x%20-%201.9.x%20-%20Transparent/app/code/community/MercadoPago/Model/Standard/Payment.php#L219

Lo único que consigo es una excepción con el mensaje: "expiration_date_to invalid".
¿Cuál sería el formato correcto?

**Comment by barbanet** [comment]
¿Sería posible conseguir respuesta a esta pregunta?

**Comment by sebagun** [comment]
@barbanet ese formato no es correcto para el campo expiration_date_to, debería ser como lo podés ver acá:
https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/receive-payments/additional-info/

Saludos

**Comment by barbanet** [comment]
Gracias @sebagun
