### ISSUE TITLE
README.md desactualizado

### ISSUE THREAD

**Issue by knifesk** [mercadopago/DEPRECATED-sdk-php#46]
Buenas, les cuento que empecé a desarrollar una nueva plataforma que utiliza mercadopago y me encontre con que la documentacion dice 

`composer require mercadopago/sdk:0.3.2`

pero el ultimo tag de version que hay es el `0.3.4`

Nada grave, pero creo que no está bueno que los que no conocen git-flow no se enteren de que hay 2 versiones más recientes que la que sugiere instalar el readme....

Saludos

**Comment by sebagun** [comment]
Ya está actualizado @knifesk 
Muchas gracias por el aviso

Saludos

**Comment by knifesk** [comment]
De nada!

edit: acá tambien :) https://www.mercadopago.com.ar/developers/en/tools/sdk/server/php/

**Comment by sebagun** [comment]
Gracias @knifesk pero el sitio levanta el mismo readme del repo GitHub. Si lo ves desactualizado refrescá, pero te aseguro que ya está corregido.

Saludos
