### ISSUE TITLE
Modo sandbox no regresa resultados (Error 503 Service Unavailable)

### ISSUE THREAD

**Issue by kazeno** [mercadopago/DEPRECATED-sdk-php#51]
Desde hace un par de semanas, al realizar un pago en modo sandbox y recibir la notificacion IPN del mismo, el servidor no regresa ningun resultado al tratar de obtener los datos de la operacion con el metodo "collections/search". No solo eso, sino que el status de la conexion es error 503 "Service Unavailable".

**Comment by alariva** [comment]
:+1: Mismo problema

**Comment by sebagun** [comment]
@kazeno @alariva ¿Podrían por favor adjuntar un log de ejemplo de request/response donde se exponga el problema?
Obviamente no adjunten credenciales reales (access_token, client_id ni client_secret).

**Comment by fedemotta** [comment]
Creo que estoy con el mismo bug desde hace un tiempo ya. Se hace imposible utilizar sandbox. Actualice a la version 0.5.2 y continua el error.

**Comment by fedemotta** [comment]
Veo que apareció un disclaimer en la documentacion de mercadopago:

```
Actualmente el Sandbox de Checkout básico se encuentra en mantenimiento y su comportamiento podría no ser el esperado. Te recomendamos que de momento realices tus pruebas utilizando Usuarios y tarjetas de prueba (ver más abajo).
```

**Comment by fedemotta** [comment]
El problema es que los usuarios y tarjetas de prueba tampoco están funcionando. 

Estoy tratando de probar el checkout basico. 

Cree 2 usuarios de prueba.

Al primero le puse las configuraciones para recibir las notificaciones de mi ambiente de QA y agregue su id y secret en mi aplicacion.

Con el otro trato de hacer una compra de $61 (con mastercard de prueba y APRO) y me aparece en la ventana (sin realizar ninguna accion en el servidor): 

```
Tuvimos un problema, intenta nuevamente
```

Mi pregunta es: Como puedo realizar pruebas? Sandbox no funciona y usuarios y tarjetas de prueba tampoco. Hay algun tiempo estimado para la resolución de estos problemas? 

Gracias

**Comment by MatayoshiMariano** [comment]
@fedemotta pudiste solucionarlo? Me pasa lo mismo!

**Comment by fedemotta** [comment]
@MatayoshiMariano en mi caso era por el sponsor_id que no funciona con los usuarios y tarjetas de prueba. Cuando lo quite funcionaron.

**Comment by MatayoshiMariano** [comment]
@fedemotta ahh okok barbaro.
De todas formas ya pude solucionar lo mio usando usuarios de prueba.
Abrazo!

**Comment by fedemotta** [comment]
@MatayoshiMariano El sandbox esta desactivado, asi que es la unica forma!

Abrazo

**Comment by IgnaG** [comment]
Agreguen esto de sacar el sponsor_id a la documentación por favor!

**Comment by matiasgordon** [comment]
Hola @fedemotta @IgnaG !

El sponsor_id es un atributo que sólo utilizan nuestros [Partners](https://partners.mercadopago.com/) para indicarnos las cuentas que están bajo su dominio. Este atributo no viene precargado en el SDK, por lo cual me llama la atención que hayan tenido problema con ello. ¿Tuvieron una integración con un Partner? ¿Cómo llegaron a enviar este atributo?

Saludos, 
Matías, MercadoPago.

**Comment by IgnaG** [comment]
@matiasgordon Soy de Tienda Nube, y nosotros tenemos la integración de tal manera que utilizamos dicho sponsor_id , por eso lo enviamos. Esto en producción anda joya, pero para testing local veníamos usando el sandbox pero como ya no funciona, ahora hacemos esto de usar usuarios de prueba etc. Pero lo que no se menciona en la docu es que si mandás un sponsor_id, no va a andar.

Ahora igual no lo vamos a mandar más si estamos en entorno local, pero hasta que no llegué a este issue no sabía por qué me fallaba. Me parece lógico que o agreguen esta advertencia en la docu, o que no rompa al mandar sponsor_id + vendedor y comprador de prueba.

Saludos y gracias por contestar!

**Comment by fedemotta** [comment]
@matiasgordon Estaba exactamente en la misma situación que @IgnaG

Deberian agregar documentación sobre el sponsor_id o al menos avisar que no funcionan los usuarios de prueba con este parametro.

Saludos

**Comment by matiasgordon** [comment]
Gracias por sus comentarios @IgnaG @fedemotta.
Lo vamos a tener en cuenta.
Saludos!

**Comment by lainz** [comment]
Hola, perdón que lo comente en este hilo, pero el sandbox ya pasado un año todavía no funciona. Mi pregunta es si puedo recibir notificaciones IPN usando usuarios de prueba.
