### ISSUE TITLE
Usuarios y tarjetas de prueba no funcionan

### ISSUE THREAD

**Issue by fedemotta** [mercadopago/DEPRECATED-sdk-php#54]
Hola,
Al hacer una compra utilizando usuarios y tarjetas de prueba (mastercard de Argentina y con prefijo APRO) devuelve un error "Tuvimos un problema, intenta nuevamente" y no puedo finalizar la compra.

Pude debugear el problema con la consola del chrome y encontré que https://www.mercadopago.com/mla/checkout/ajax/postValidationErrorEvent esta devolviendo un error:

details:[{"key":"ajaxStatus","value":200},{"key":"error","value":{"action":"error"}},{"key":"paymentMethodId","value":"master"},{"key":"cardId","value":"master"},{"key":"payerId","value":"97417950"},{"key":"cardTokenId","value":"b561b9e08305ad14b74b328c188c125a"}]
event:unknownMessageForErrorOnPostPayment
status:500

Ojalá puedan resolverlo por que sumado al issue #51 hace imposible testear la aplicación, por lo que estoy totalmente bloqueado para continuar desarrollando con mercadopago.

Gracias

**Comment by matiasgordon** [comment]
Hola @fedemotta !

Por favor puedes enviarnos la preferencia de pago con la que obtuviste el error?

Muchas gracias!

**Comment by fedemotta** [comment]
Ya está resuelto. Es por el sponsor_id que le estaba pasando al iframe. No funciona si se deja el sponsor_id. Deberían mejorar la documentacion sobre el sponsor_id, no hay nada sobre eso.

Gracias

**Comment by jmaturrano** [comment]
Disculpa, me pasa lo mismo. Pero qué es el sponsor id?, porque hay otro campo que es client_id. Cómo obtengo el sponsor id?
