### ISSUE TITLE
¿Funcionan Usuarios y Tarjetas de prueba con MercadoPago Applications?

### ISSUE THREAD

**Issue by famigone** [mercadopago/DEPRECATED-sdk-php#57]
Estimados, tengo una aplicación y dos usuarios de prueba: A y B. Mi aplicación, cobra al usuario B(comprador) en nombre del usuario A (vendedor). 

El usuario A se encuentra conectado a mi aplicación, ya autorizó la misma. Luego el usuario B quiere pagar un ítem cualquiera utilizando las tarjetas de prueba que ustedes proporcionan. 

Invariablemente me retorna `Tuvimos un problema, intenta nuevamente`.

Es posible utilizar usuarios y tarjetas de prueba en dicho escenario? gracias.

**Comment by matiasgordon** [comment]
Hola @cognitivaxx !

Los 3 usuarios (el dueño de la aplicación, el vendedor y el comprador) deben ser de prueba. 

En tu caso, el dueño es un usuario real.

Saludos

**Comment by famigone** [comment]
Ahora sí, muchas gracias por tu valiosa y rápida respuesta.
