### ISSUE TITLE
Notificaciones para operaciones "Comisión por uso de plataforma de terceros" (MP Applications)

### ISSUE THREAD

**Issue by famigone** [mercadopago/DEPRECATED-sdk-php#58]
Estimados, tengo 3 usuarios de prueba, A es el dueño, B autorizó la aplicación A y C pagó a B. Tengo un cobro de prueba creado y puedo verlo desde el usuario de prueba vendedor. 

Cuando presiono el botón **Probar URL** de la [Configuración de Notificaciones](https://www.mercadopago.com/mla/herramientas/notificaciones) para CheckOut básico, la respuesta que obtengo es: "_Request fail, No hay comunicación entre servidores_". Sin embargo, mi URL es accesible y la atiende el código que se encuentra en el instructivo. 

¿Será que con operaciones de usuarios de prueba no se activan las notificaciones?

**Comment by matiasgordon** [comment]
Hola @cognitivaxx ! Podés indicarnos el id de pago?

La URL la configuraste en el dueño de la app (A) o en el vendedor (B)?

Saludos.

**Comment by famigone** [comment]
Matías, había configurado la URL en el vendedor(B) lo cual supongo que es incorrecto. Ahora la configuré en el dueño de la app (A). El problema ahora es el siguiente: me dice que debo tener al menos un pago registrado. 

Desde la cuenta MP del dueño, puedo ver el monto de comisión (nro operación **1838259837**) correspondiente a la Comisión por uso de plataforma de terceros que efectuó el vendedor B con el cobro **1838259837**. 

El caso es que presiono el botón desde
-  el usuario Dueño, me dice que **No tengo Pagos Registrados**. 
-  el usuario vendedor, me dice que **No hay comunicación entre servidores**.

**Comment by famigone** [comment]
Bueno, el problema nunca se solucionó, sin embargo, las notificaciones llegan satistactoriamente. Cierro el issues.

Saludos.
