### ISSUE TITLE
External_reference en NULL en Notificaciones (Checout Básico - MP Applications - Usuarios de Prueba)

### ISSUE THREAD

**Issue by famigone** [mercadopago/DEPRECATED-sdk-php#59]
Estimados, por alguna razón al recibir la notificación de un cobro, el valor de EXTERNAL_REFERENCE me retorna siempre en NULL. Quiero enviar allí el id del ítem que esta siendo pagado, de otra forma, no puedo trazar la operación en mi base de datos. 
Alguna sugerencia? (uso checkout básico, con MPApplications, usuarios y tarjetas de prueba.)
### Así lo envío:

 $preference_data = array(
            "items" => array(
                array(
                    "title" => "Inscripción al evento " . $item->nombrecorto,
                    "external_reference" => $item->id,
                    "description" => $item->descripcion,
                    "quantity" => 1,
                    "unit_price" => 50,
                    "currency_id" => "ARS",
                    "picture_url" => "https://www.mercadopago.com/org-img/MP3/home/logomp3.gif"
                )
            ),
        );
### Así lo busco:

$external_reference = $payment_info['response']['collection']['external_reference'];

**Comment by barbanet** [comment]
En el array, external_reference, debería esstar al nivel del nodo items, no dentro de un item.
Es la referencia del pago, no del item. https://www.mercadopago.com.ar/developers/en/api-docs/custom-checkout/create-payments/

**Comment by famigone** [comment]
Fantástico, muchas gracias Damián.
