### ISSUE TITLE
[RFC] Discourage standalone setup/usage

### ISSUE THREAD

**Issue by phansys** [mercadopago/DEPRECATED-sdk-php#63]
Remove references and examples for standalone usages without Composer:
- https://github.com/mercadopago/sdk-php#by-downloading
- https://github.com/mercadopago/sdk-php#get-payment-data

If this RFC is accepted, I can create a PR changing `README.md` based on this premise.

**Comment by phansys** [comment]
@joelibaceta, could you please provide some context about the reason for closing this issue?
Thank you in advance.

**Comment by joelibaceta** [comment]
@phansys  Because this sdk is a legacy version, we are closing issues about  new features or changes not strictly necessary to do.

**Comment by joelibaceta** [comment]
You can find the new version in https://github.com/mercadopago/dx-php
