### ISSUE TITLE
BUG: En modo modal el botón de pago no se ve (queda escondido)

### ISSUE THREAD

**Issue by maxitromer** [mercadopago/DEPRECATED-sdk-php#65]
Al parecer el HEIGHT que contiene el modal no termina de acomodarse y como el DIV interno es de mayor tamaño aparece un scroll que esconde el botón de pago.

Mucha gente nos ha escrito por el soporte porque no entienden como pagar y probablemente el problema sea que no están encontrando el botón de pago.

Les dejo una imagen en donde se muestra el problema, abajo se ve parte del botón (flecha roja), pero no se lo alcanza a ver completo y probablemente la gente no entienda que es ni como hacer para mostrarlo completo.

![mp](https://cloud.githubusercontent.com/assets/6311835/16845828/a11d3d44-49c0-11e6-8587-89b4e393d1d8.png)

Otro problema es que el borde gris exterior tampoco está bien encuadrado y se ve como cortado.

**Comment by wertgroup** [comment]
Hola, pudiste solucionar esto? a mi me pasa lo mismo con el borde gris

**Comment by joelibaceta** [comment]
@maxitromer entiendo que esto ya debería estar resuelto en el nuevo formulario ( esa es una version legacy )
