### ISSUE TITLE
No obtengo el id del pago en la URL

### ISSUE THREAD

**Issue by nicogaldo** [mercadopago/DEPRECATED-sdk-php#66]
Para poder usar las notificaciones de pago, necesito el id del pago, que tendria que venir por la url, pero no está.

La url que me devuelve es asi:

```
misitio.com/.../mpsuccess.php?collection_id=1268393&collection_status=approved&preference_id=164595029-2325b15e-d6f8-41e2-9a00-a722e061061f&external_reference=F1&payment_type=credit_card&merchant_order_id=null
```

Al boton de pago lo tengo configurado de la siguiente manera:

```
$mp = new MP($mpId, $mpSecret);
$mp->sandbox_mode($sandbox);

$preference_data = array(
    "items" => array(
        array(
            "id" => $sale['reference'],
            "title" => $sale['product_name'],
            "currency_id" => $currency['iso_code'],
            "quantity" => 1,
            "unit_price" => intval($sale['price']),
            "category_id" => 'learnings'
        )
    ),
    "payer" => array(
        "name" => $userInfo['firstname'],
        "surname" => $userInfo['lastname'],
        "email" => $userInfo['email'],
        "date_created" => api_format_date($sale['date'], DATE_FORMAT_LONG_NO_DAY)
    ),
    "back_urls" => array(
        "success" => api_get_path(WEB_PLUGIN_PATH) .'buycourses/src/mpsuccess.php',
        "failure" => api_get_path(WEB_PLUGIN_PATH) .'buycourses/src/mpnone.php',
        "pending" => "http://www.pending.com"
    ),
    "external_reference" => "F1".$sale['reference']
);

$preference = $mp->create_preference($preference_data);
```

Según la [documentacion](https://www.mercadopago.com.ar/developers/en/related/basic-sandbox/) debo utilizar el siguinte codigo, que busca con un `GET`el valor del parametro `id`

```
$payment_info = $mp->get_payment_info($_GET["id"]);

if ($payment_info["status"] == 200) {
    print_r($payment_info["response"]);
}
```

Pero me devuelve un error: `Notice: Undefined index: id` `MP->get_payment(NULL)`

Para su información estoy utilizando el modo **sandbox** , un usuario real (para las key), y un usuario comprador invitado (utiliza el email de registro en el sitio).
También tengo configurado la misma url de `back_urls` en la [configuración de notificaciones ipn](https://www.mercadopago.com.ar/ipn-notifications) (el archivo mpsuccess.php)

**Comment by xanok** [comment]
Hmm
So this error is happening since 3rd Aug? We are in trouble then

**Comment by ivan-e** [comment]
el Id es el collection_id=1268393. Cambia los $_GET['id'] a $_GET['collection_id'] o armate otra url que se redireccione como http://www.tusitio.com.ar/ipn/ipn.php?topic=payment&id=1268393
