### ISSUE TITLE
Mantain a changelog

### ISSUE THREAD

**Issue by fedeisas** [mercadopago/DEPRECATED-sdk-php#70]
Sería genial tener un Changelog para poder mantener actualizada esta integración. Gracias!

**Comment by matiasgordon** [comment]
Gracias por la sugerencia, lo haremos a partir de la próxima versión. Saludos.

**Comment by joelibaceta** [comment]
Les comparto la nueva version del SDK, https://github.com/mercadopago/dx-php pueden ver las notas de cada Release. 

Para cambios generales de MercadoPago pueden revisar el **changelog** del developer site https://www.mercadopago.com.ar/developers/es/guides/changelog/2018/
