### ISSUE TITLE
test

### ISSUE THREAD

**Issue by JavierSolis** [mercadopago/DEPRECATED-sdk-php#71]
Hola, como se hace para realizar un prueba de notificación de pago, por el tipo tycket, por ahora solo llego al paso de la reserva del pago, pero el deposito como se simula y la notificación de que se realizo el deposito del pago.

Gracias

**Comment by ceciunt** [comment]
Pudiste resolverlo, Javier?, yo estoy con el mismo tema o similar.  Habrá alguna manera de que mercadopago vuelva al sistema de uno, para confirmar que se realizó el pago?... tomando un id?.
Gracias!

**Comment by JavierSolis** [comment]
Hola, ps nada, por otro hilo con la misma duda me dicen que no existe notificaciones de prueba para pagos por tycket, por ahora solo me queda hacer pruebas con pagos reales, usando el costo minimo de 5 soles, ojala lo implementen.
