### ISSUE TITLE
get_payment_info SANDBOX - no encuentra el pago

### ISSUE THREAD

**Issue by MatiasL13** [mercadopago/DEPRECATED-sdk-php#75]
Buenas, quería consultar si funciona el get_payment_info en sandbox.

efectué un pago con esta configuracion

```
$preference_data = array(
                "items" => array(
                    array(
                    "id" => "8877",
                    "title" => $fila["nombre"],
                    "currency_id" => "ARS",
                    "description" => $fila["descripcion"],
                    "category_id" => "-",
                    "quantity" => 1,
                    "unit_price" => (int)$fila["precio"],
                    "additional_info" => $usuario->id
                )
                ),
                 "notification_url" => "http://www.web.com.ar/ipn"
            ); 
```
tuve que agregar el  `"notification_url" => "http://www.web.com.ar/ipn" ` en la configuración porque desde https://www.mercadopago.com.ar/ipn-notifications/ no me toma el link en sandbox (en  producion si envia la notificacion)

Una vez que creo un pago de prueba y me dice que esta todo OK, veo que llega la notificacion a la pagina que configure(puedo confirmar que llega porque cada vez que se llama la pagina se crea un LOG con el GET["ID"] que llega) pero el ID del pago que me llega me tira el siguiente error 

` Uncaught exception 'MercadoPagoException' with message 'not_found `
como si no existiera el pago que acaba de crearse.

pd: el codigo esta seteado en 	$mp->sandbox_mode(true);

Saludos!

**Comment by MatiasL13** [comment]
bueno, por lo que estuve viendo sandbox no funciona y las pruebas se hacen en produccion con usuarios de test. asi que ya esta

**Comment by tesoner** [comment]
@MatiasL13  has resuelto el problema ? Tengo un pequeño error.  https://www.mercadopago.com.ar/ipn-notifications/
Esta página no me acepta las URL, no tengo https, y al parecer se necesita: https://wordpress.org/support/topic/la-url-ingresada-no-responde-un-http-status-correcto-debe-responder-200-o-201/

Tú app está rodando bien sin protocolo https ?

**Comment by MatiasL13** [comment]
@tes1oner
el problema era que no anda sandbox, asi que tenes que usarlo en modo productivo.
 si me llegan bien las notificaciones por IPN  y no tengo https, 
para saber si llegaban las notificaciones  hice un  archivo de log de prueba, asi me aseguro por lo menos que MP esta enviando algo, una vez que vi que funcionaba lo borre.
```

//guardo log
	$file = 'logIPN.txt';
	// Open the file to get existing content
	$current = file_get_contents($file);
	// Append a new person to the file
	$current .= $_GET["id"]."\n//////";
	// Write the contents back to the file
	file_put_contents($file, $current);
```

en el archivo te va a dejar guardado todos los ID de pagos que te envia MP

**Comment by tesoner** [comment]
@MatiasL13 Gracias por responder. Pues sí algo así más o menos tengo y ya logré poner la URL sin embargo no me llegan notificaciones. Pero sí, supongo que son fallas en el sandbox porque si lo uso no se procesa ningun pago.

**Comment by MatiasL13** [comment]
@tes1oner  si el sandbox no funciona para nada.
para hacer pruebas tenes que poner $mp->sandbox_mode(false);
y usar cuentas test en prod.

https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/test/test-users/

creas dos cuentas y probas todo lo que queres
(vas a tener que configurar devuelta el IPN con la cuenta de prueba )

**Comment by dann95** [comment]
@MatiasL13 hola amigo, he tenido el mismo problema, puedes explicarme como puedo probar las notificaciones en mi sistema en sandbox?

**Comment by MatiasL13** [comment]
hola, @dann95  , el tema es q no funciona sandbox, como puse en los mensajes anteriores tenes que hacer las pruebas en el ambiente productivo de MP pero con  cuentas de test(2 cuentas, una compradora y otra vendedora)
en este link te explican como se crean dichas cuentas.
https://www.mercadopago.com.ar/developers/es/related/test-users/

dps probas comprar algo de una cuenta a la otra para ver si funciona la implementacion que hiciste en tu pagina.

Saludos!

**Comment by dann95** [comment]
@MatiasL13 pero yo trabajo con checkout transpaente(custom) y nunca necessito de claves de comprador ._.

**Comment by dann95** [comment]
@MatiasL13 por eso no consigo entender, nito crear una cuenta de prueba? y en ella creo una aplicacion y agarro las credenciales? és eso?

**Comment by MatiasL13** [comment]
@dann95 estas haciendo un checkout personalizado en vez del basico ? deberia ser igual, vos cuando inicializas las librerias pones la api key de una de las cuentas test q creaste, y cuando queres comprar el prodcuto para probarlo, lo compras logeandote con otra cuenta test diferente a la vendedora.

si ves que la integracion que hiciste funciona, le cambias las key del usuario test por el usuario productivo que vas a utilizar.

**Comment by dann95** [comment]
@MatiasL13 no, no és checkout custom basico, es el transparente, namas la persona pone la tarjeta, nunca ve el nombre mercado pago xD

**Comment by levitarmouse** [comment]
Buenas!
Pudieron hacer andar el Checkout Personalizado???

Abrí una nueva pregunta en google grups por este mismo tema ... no logro hacerlo andar.
https://groups.google.com/forum/#!category-topic/mercadopago-developers/apis/azK75DRKmH4

Siempre con ... 2043 Invalid users involved!!!!

Cualquier ayuda será agradecida

**Comment by diegonella** [comment]
Hola, hiciste los usuarios de prueba?

**Comment by joelibaceta** [comment]
El endpoint `/collection/notifications/` ha sido deprecado, se debe usar `/v1/payments/ `en su lugar, (ver nota de deprecación https://www.mercadopago.com.ar/developers/es/guides/localization/migrating-v0-v1)

La version 0.5.3 de este SDK usa este nuevo endpoint y debería permitir encontrar los pagos sandbox.
