### ISSUE TITLE
Search payment con external_reference no muestra el collection result

### ISSUE THREAD

**Issue by vousys** [mercadopago/DEPRECATED-sdk-php#80]
Chicos estoy teniendo un problema q aparecio ayer. Usamos el SDK viejo porque tenemos apps viejas, y siempre hacemos la busqueda via el external_reference. 

EJ: 
/collections/search?external_reference=520-2964-9-2-NTIw&offset=0&limit=0&access_token=APP_USR-385260425320669-020206-b5b807e13f4794d6e6c63a123f18deb1__K_D__-43987228

pero ahora nos Devuelve:
Array
(
    [status] => 200
    [response] => Array
        (
            [paging] => Array
                (
                    [total] => 1
                    [limit] => 0
                    [offset] => 0
                )

            [results] => Array
                (
                )

        )

)

Y necesitamos todo el detalle de los pagos, es un error eso?

L​o postee en los foros, porq a otro tb le paso:
http://es.stackoverflow.com/questions/47259/api-mercado-pago-inconsistencia-en-collections-search

**Comment by estcap2** [comment]
En el mismo thread que mencionás ya figura una posible solución (que a mí me sirvió, ahora a mí me está andando bien)
Pareciera que hay una inconsistencia de como toma el parametro `limit` dependiendo de como mandas los parámetros en `search_payment();` 

Intenta mandándolo con sus tres parámetros explícitos.
Por ejemplo:

```
//Ejemplo para buscar un pago individual según una referencia externa:
$filters = array(
                    "external_reference" => $referencia_mercadopago
                );
                $search_result = $mp->search_payment($filters); // Esto antes funcionaba, 
//ahora devuelve  un array vacío.
// Asume que limit = 0 es que no querés ningún resultado 

                $search_result = $mp->search_payment($filters, 0, 1); //Esto encuentra el pago,
// poniéndole explícitamente offset 0 y limit 1.
```


Saludos,

**Comment by vousys** [comment]
Sisi ya lo solucione con eso el otro dia, gracias!



[image: photo]

<http://facebook.com/vousys>  <http://us.linkedin.com/in/vosorio>
<http://twitter.com/vousys>  <http://instagram.com/vousys>
<http://behance.net/vousys>
Vero Osorio
CEO & Founder, VOUSYS
+54 911 4481 3751  <+54+911+4481+3751>*•* Skype: vousys
<#UNIQUE_ID_SafeHtmlFilter_> *•*
 http://www.vousys.com  <http://www.vousys.com>*•* vosorio@vousys.com
<vosorio@vousys.com>*•*

**Comment by fgilio** [comment]
Gracias! Me estaba pasando esto mismo

**Comment by maurogioberti** [comment]
@estcap2 gracias, la verdad que un dolor de cabeza, lo del tema de limit 0, no lo dice ni en la documentación de la api, ni en los ejemplos de la misma.

**Comment by fgilio** [comment]
Es lo más contraintuitivo que hay

**Comment by mauromm** [comment]
Esta funcionando este servicio? Estoy haciendo lo mismo que comentar arriba con el offset y limit, pero siempre me viene vacio... no estoy encontrando manera de que me traiga resultados. Y son pagos que estan impactados correctamente en MP.

**Comment by fgilio** [comment]
Hola @mauromm! A ver, lo pruebo y actualizo acá el comment

**EDIT:** Pareciera estar funcionando, lo hice así:
```php
$searchResult = $mp->search_payment([
    "external_reference" => "221345334234123"
], 0, 100);
```
\* Ese `external_reference` es a modo de ejemplo

**Comment by mauromm** [comment]
Gracias @fgilio .Ya encontré cual era el problema. Tenia un token incorrecto...

**Comment by danicode** [comment]
Buenas.

No logre que funcioné la búsqueda por medio de search_payment, posiblemente en algo le este errando, pero logre obtener los pagos de la siguiente forma por si a alguien le sirve.

```php
$mp = new \MP('ACCESS_TOKEN');
$payment = $mp->get("/v1/payments/search?range=date_created&begin_date=NOW-1MONTH&end_date=NOW&status=approved&operation_type=regular_payment");
return $payment;
```

Saludos, happy coding! :)

**Comment by maurogioberti** [comment]
A mi lo del limit me funcionó 10 puntos, normalmente no tengo problemas, a veces lo que pasa el host de mercadolibre no responde pero no es seguido, normalmente anda todo bien.

**Comment by pabloldeoliveira** [comment]
Efectivamente ahora si no le indicamos el parámetro limit no devuelve las colecciones. La documentación de MP tampoco ayuda y realmente desorienta, así que bueno, vine a encontrar la respuesta acá.

**Comment by fgilio** [comment]
Efectivamente, esto es un garrón. De hecho la situación general de toda la experiencia de cara a developers es tan pobre que me gustaría no tener que soportar MercadoPago.

**Comment by brianirvana** [comment]
¿hay alguna forma de que el limit devuelva "X" cantidad de últimos limit?, osea si son 100 pagos, yo quiero consultar los últimos 10 nada más...
