### ISSUE TITLE
Colocar os namespace 

### ISSUE THREAD

**Issue by allanmcarvalho** [mercadopago/DEPRECATED-sdk-php#84]
A maioria das maneiras de se programar usando PHP utiliza namespaces para fazer o autoload. Acredito que seja só inserir no top da lib... 
Ex. namespace /ML;

**Comment by mozgbrasil** [comment]
+1

**Comment by joelibaceta** [comment]
@allanmcarvalho thanks for the suggestion, we are using namespaces in the new version https://github.com/mercadopago/dx-php
