### ISSUE TITLE
IPN Notificación

### ISSUE THREAD

**Issue by AgustinQuetto** [mercadopago/DEPRECATED-sdk-php#86]
Hola compañeros,

poseo la siguiente duda. 

¿Los IPN redirecciona al usuario en el momento en que se realizó la compra obteniendo a su vez la respuesta que corresponda? Por ejemplo, si se redirecciona en el momento podría utilizar variables de sesión, caso contrario debería colocar cada compra en una db para realizar las comparaciones con las variables obtenidas del pago junto al ipn.

¿De que forma puedo eliminar los métodos de pago en efectivo? 

Se que es una mala práctica, pero al ser algo temporal, necesitaría confirmar mis dudas.
Gracias por su tiempo.

**Comment by AgustinQuetto** [comment]
O podría enviar mi variable de sesión de usuario en el pago para luego tomarla aunque la sesión esté cerrada por si notifica. Debería ser una opción.

**Comment by knifesk** [comment]
Los IPN los manda MercadoPago via POST a tu server, es decir. Los manda el SERVER de MercadoPago a tu host.. no el cliente.. 

Y si, tenes q almacenar cada compra en una DB, y cuando recibis el IPN marcala como confirmada.. Antes es imposible que sepas si el usuario realmente pago o no..

con respecto a eliminar los pagos en efectivo, cuando creas la preferencia de pago para el checkout que estas procesando podes utilizar el atributo `payment_methods` y sus atributos específicos para definir que medios de pagos vas a recibir.. aca tenes la referencia: https://www.mercadopago.com.ar/developers/en/api-docs/basic-checkout/checkout-preferences/

No quiero sonar mala onda, pero todo lo que preguntas está en la documentación, deberías tomarte unas 2hs para leerla de punta a punta asi entendes bien como funciona la plataforma.. vos pensa que estas manejando guita a través de esto, y una mala implementación podría llevar a que pierdas guita vos o tu cliente.

**Comment by AgustinQuetto** [comment]
Gracias @knifest por la pronta respuesta. Sí, la leí completa pero prefiero preguntar a quienes ya tengan experiencia en la API para justamente ahorrar horas de testeo, trabajo y despejarme dudas que podrían darme vulnerabilidades.

No, no fue mala onda. Todo lo contrario. Siempre que creo un issue busco sinceridad.

Gracias! Resuelto y cierro.
