### ISSUE TITLE
Shipments receiver_address not working

### ISSUE THREAD

**Issue by pedrodevoto** [mercadopago/DEPRECATED-sdk-php#91]
When I set `receiver_address` into `shipments` and then I get redirected to MercadoPago's website, the address is not there and I have to manually enter it again. Is it supposed to work like this or is it a bug?

```php
$shipments = array(
"mode" => "me2",
"dimensions" => $dimensions,
"local_pickup" => false,
"default_shipping_method" => (int)$shipping_method,
"receiver_address" => array(
        "zip_code" => "1430",
        "street_number"=> 100,
        "street_name"=> "Libertad",
        "floor"=> 4,
        "apartment"=> "C"
    )
);
```

**Comment by leandroahmad** [comment]
The bug is from the API, not the SDK. It still doesn't work.

**Comment by rockscripts** [comment]
Bueno, esta solucion debe ser importante, porque nadie quiere llenar datos de envio dos veces si se puede pasar al formulario de envio - pago directamente en mercadopago.
