### ISSUE TITLE
Error "Test tokens are not allowed" al crear preference

### ISSUE THREAD

**Issue by pablojp** [mercadopago/DEPRECATED-sdk-php#92]
Estoy utilizando el token de test y el mismo codigo ayer me funcionaba para crear un preference, pero hoy me responde un error 403 - "Test tokens are not allowed". 
Hay algun problema con el sandbox de la api de mercadopago?

**Comment by Tomicapo** [comment]
Hola. Acabo de instalar la librería via composer y lo primero que me dice es este error.
Alguien puede aportar un poco de luz por favor?

**Comment by joelibaceta** [comment]
No es necesario usar un `access_token` de test para crear preferencias ya que las preferencias incluyen en uno de sus atributos el `sandbox_init_point` que tiene como fin, proveer la url por la cual se inicia el Checkout en modo sandbox.
