### ISSUE TITLE
MercadoPagoException - Unauthorized use of live credentials 

### ISSUE THREAD

**Issue by informaticosgb** [mercadopago/DEPRECATED-sdk-php#93]
Hola. Estoy tratando de actualizar el status de un pago pero me aparece el siguiente error: 

![image](https://user-images.githubusercontent.com/4468829/27739913-9439e282-5d86-11e7-9f1e-97aa4236b2e4.png)

Mi .php es el siguiente: 

![image](https://user-images.githubusercontent.com/4468829/27740004-e9304c54-5d86-11e7-8be7-aee97cd8b570.png)

Si alguien me puede decir que estoy haciendo mal estaría agradecido ! Saludos..

**Comment by rakesh-ideal** [comment]
I got same problem

**Comment by libasoles** [comment]
Novedades de esto? Me esta pasando al postear.
```

$response = $mp->post (
        array(
            "uri" => "/v1/payments?access_token={$token}", 
            "authenticate" => false,
            "data" => [
                "transaction_amount"=> $amount,
                "payment_method_id"=> "account_money",
                "collector"=> ["email"=> $email],
                "external_reference"=> "abc",
                "description"=> "xyz"
            ]
        )
    );    
```

btw, estoy usando sandbox.

**Comment by libasoles** [comment]
Encontré la respuesta. La da horacio Casatti (team MP) aca: 

https://groups.google.com/forum/embed/?place=forum/mercadopago-developers&showsearch=true&showpopout=true&showtabs=false&hl=es_AR#!searchin/mercadopago-developers/Unauthorized$20use$20of$20live$20credentials/mercadopago-developers/hkGzBrKQQs0/1Zyvr8S6FQAJ

Basicamente, no sirve usar `sandbox_mode()`. Hay que poner el token manualmente, que se consigue aca: https://www.mercadopago.com/mla/account/credentials

De hecho, si se fijan, al hacer: 

```
$mp = new MP ($credenciales['client_id'], $credenciales['client_secret']);
$mp->sandbox_mode(true);
$token = $mp->get_access_token();
echo $token;
```

Ese `$token` es el productivo y no el de sandbox.

Para mi es incoherente que haya un metodo en la librería que en teoría activa sandbox pero que en realidad no lo hace.

**Comment by joelibaceta** [comment]
Para consultar o realizar pagos, se debe usar el access_token de la aplicación, no el token live ( client_id + client_secret )
