### ISSUE TITLE
Invalid card token - 2062

### ISSUE THREAD

**Issue by pberniker** [mercadopago/DEPRECATED-sdk-php#98]
Cuando quiero realizar una reserva de fondos, siguiendo el ejemplo que esta en https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/two-step-payments/
me da el error "Invalid card token - 2062". 

Mi codigo es el siguiente:

$mp = new MP(MP_TOKEN);

    $publicKey = MP_PUBLIC_KEY;
    $request   = "/v1/card_tokens?public_key=$publicKey";
    $res       = $mp->post($request);
    $response  = $res["response"];
    $id        = $response["id"];
    
    $payment_data = array(
        "transaction_amount" => 100,
        "token" => $id,
        "description" => "Title of what you are paying for",
        "installments" => 1,
        "payment_method_id" => "visa",
        "payer" => array (
            "email" => "test_user_19653727@testuser.com"
        ),
        "capture" => false
    );

    $payment = $mp->post("/v1/payments", $payment_data);

me podrian ayudar?

**Comment by joelibaceta** [comment]
Este canal esta dedicado para la discusión sobre bugs en el sdk Legacy.

Te sugiero revisar la nueva versión del SDK (https://github.com/mercadopago/dx-php)

Te comparto también el canal de soporte oficial para integradores. http://www.mercadopago.com.ar/developers/es/support
